### ISSUE TITLE
ODataOpenTypeSample fails to deserialize

### ISSUE THREAD

**Issue by bdebaere** [OData/ODataSamples#109]
When issuing a **POST** request to /odata/Accounts with the JSON below and Content-Type header set to application/json the properties are all null. **PUT** requests suffer from the same problem. While PATCH requests do not...

![image](https://user-images.githubusercontent.com/1436449/51463311-31717e00-1d63-11e9-8be2-5e40f87742e8.png)

```csharp
{
    "Id": 1,
    "Name": "Name1",
    "Gender@odata.type": "#ODataOpenTypeSample.Gender",
    "Gender": "Male",
    "Emails@odata.type": "#Collection(String)",
    "Emails": [
        "a@a.com",
        "b@b.com"
    ],
    "Address": {
        "City": "Redmond",
        "Street": "1 Microsoft Way",
        "Country": "US"
    }
}
```

This is the response:
```csharp
{
    "@odata.context": "http://localhost:33655/odata/$metadata#Accounts/$entity",
    "Id": 3,
    "Name": null,
    "Address": null
}
```

Sending the JSON below leads to the same issue.
```csharp
{
    "Id": 1,
    "Name": "Name1",
    "Address": {
        "City": "Redmond",
        "Street": "1 Microsoft Way",
        "Country": "US"
    }
}
```

**Comment by KanishManuja-MS** [comment]
Should you be using [FromBody] Attribute before the parameter?
