### ISSUE TITLE
Unable to check / call TransientAction

### ISSUE THREAD

**Issue by JanEggers** [OData/ODataSamples#24]
HI,

I Have an Odata V4 Controller setup and i am using TransientAction to express if i an action can be eecuted in the current state so i dont have to have duplicated code in client and server.

This works fine with angular and js in general.

i can do: 

var actionLink= item['#Action'];;
if (!actionLink) {
   return;
}
$http.post(actionLink.target, {});
....

I didnt find a way to do that with odata client as the proxy generator does not map functions in the objects.

i found OperationDescriptions on the EntityDescription but they are always present. 

can anyone help me with this issue?

btw. its a little ugly to only be able to call actions with an extension on DataServiceQuerySingle<T>.

why isnt the selflink and all the other selfdocumentation ( editlink etc. )only available via entityDescriptor and not part of each object?

**Comment by jricke** [comment]
Did you ever find a solution to conditionally add an Action to an EntityType? In v4, when returning null from HasActionLink the response still includes the action.
