### ISSUE TITLE
Update TripPin service to support capability vocabulary

### ISSUE THREAD

**Issue by congysu** [OData/ODataSamples#26]
https://github.com/OData/ODataSamples/tree/master/Scenarios/TripPin
Either the ODataLib one, or the Web API one to support capability vocabulary done in ODataLib 6.13 and OData Web API 5.7.
Refer an existing sample: https://github.com/OData/ODataSamples/tree/master/WebApi/v4/ODataCapabilitiesVocabularySample

**Comment by xuzhg** [comment]
Updated. Thanks.
